### ISSUE TITLE
ESLint ERROR in SQL query with subquery:- Internal error: Cannot read properties of undefined (reading 'relname')

### ISSUE THREAD

**Issue by mustakimkr** [ts-safeql/safeql#176]
**Describe the bug**
I encountered an internal error while executing a SQL query containing a subquery. The error message I received specifically points to an issue related to accessing the 'relname' property.

**To Reproduce**

1. Use any valid SQL query with subquery in an environment configured with the "@ts-safeql/eslint-plugin" version 2.0.0.
2. Ensure that the SQL query includes a subquery, as shown in the code snippet.

**code snippet**
```
const assigned_properties = await request.server.db.query(sql`
SELECT
    properties.id,
    properties."name",
    CASE WHEN assigned_roles.role_id IS NULL THEN false ELSE true END AS is_assigned
FROM
    property_user
LEFT JOIN properties ON properties.id = property_user.property_id
LEFT JOIN (
    SELECT property_id, role_id
    FROM property_role
    WHERE role_id = ${request.params.role_id}
) AS assigned_roles ON assigned_roles.property_id = property_user.property_id
WHERE
    user_id = ${request.user.id};
       `);
```
**eslint error**

`Internal error: Cannot read properties of undefined (reading 'relname')eslint[@ts-safeql/check-sql](https://github.com/ts-safeql/safeql)`

**Expected behavior**
The plugin should not encounter any error as the SQL query is alright and generates types for that query. 
e.g.
```
 const assigned_properties = await request.server.db.query<{
      id: number | null;
      name: string | null;
      is_assigned: boolean | null;
    }>(sql`
SELECT
    properties.id,
    properties."name",
    CASE WHEN assigned_roles.role_id IS NULL THEN false ELSE true END AS is_assigned
FROM
    property_user
LEFT JOIN properties ON properties.id = property_user.property_id
LEFT JOIN (
    SELECT property_id, role_id
    FROM property_role
    WHERE role_id = ${request.params.role_id}
) AS assigned_roles ON assigned_roles.property_id = property_user.property_id
WHERE
    user_id = ${request.user.id};
       `);
```

**Screenshots**
<img width="1230" alt="Screenshot 2023-08-09 at 10 22 51 PM" src="https://github.com/ts-safeql/safeql/assets/46971357/5b5b7d1f-c970-4680-8a5a-445ec6419d7c">

**Desktop (please complete the following information):**
 - OS: macOS
 - PostgreSQL version: 14.6
 - "@ts-safeql/eslint-plugin" version: 2.0.0

**Additional context**
It's important to note that the error specifically relates to queries with subqueries. Given that the SQL query itself is correct, the issue seems to be within the "@ts-safeql/eslint-plugin" when processing queries of this nature. Resolving this bug is crucial to maintaining the plugin's ability to accurately and safely generate type definitions for SQL queries, including those with subqueries.

**Comment by Newbie012** [comment]
Fixed in [2.0.1](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%402.0.1)

**Comment by mustakimkr** [comment]
Updated to @ts-safeql/eslint-plugin@2.0.1.
But still the same error `Internal error: Cannot read properties of undefined (reading 'relname')eslint[@ts-safeql/check-sql](https://github.com/ts-safeql/safeql)`

So when I dig into the fixed [2.0.1](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%402.0.1).
I found that the test _"select from subselect with an alias"_ which works fine.
`SELECT subselect.id FROM (SELECT * FROM caregiver) AS subselect;`

But when I select and join a subquery the same error occurs.
```
    SELECT subselect.id FROM users
     LEFT JOIN (SELECT * FROM users) AS subselect on subselect.id =users.id 
```
`Internal error: Cannot read properties of undefined (reading 'relname')eslint[@ts-safeql/check-sql](https://github.com/ts-safeql/safeql)`

So, I think there is still a bug.

**Comment by Newbie012** [comment]
Thanks for taking your time reporting this bug 🙂

Just pushed a fix in [2.0.2](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%402.0.2)

**Comment by mustakimkr** [comment]
Great, works fine.

Thank you so much for your blazingly fast response.
