### ISSUE TITLE
Regression: inference of subquery aliased field name and type (`number` instead of `boolean`)

### ISSUE THREAD

**Issue by karlhorky** [ts-safeql/safeql#362]
**Describe the bug**

SafeQL infers that the field in the subquery is `id` and not the aliased name `rsvped`:

```ts
// 💥 Query has incorrect type annotation.
//    Expected: { rsvped: boolean }[]
//      Actual: { id: number }[]
await sql<{ rsvped: boolean }[]>`
  SELECT
    x.*
  FROM
    (
      SELECT
        event_rsvps.id IS NOT NULL AS rsvped
      FROM
        event_rsvps
    ) x
`
```

**Workaround**

1. Use explicit field names (`x.rsvped` instead of `x.*`)
2. Switch `boolean` type to `boolean | null` (not accurate, but I think this is a separate SafeQL nullability inference error)

```ts
// ✅
await sql<{ rsvped: boolean | null }[]>`
  SELECT
    x.rsvped
  FROM
    (
      SELECT
        event_rsvps.id IS NOT NULL AS rsvped
      FROM
        event_rsvps
    ) x
`
```

**To Reproduce**

See above

**Expected behavior**

Inference of the aliased name `rsvped` in the subquery

**Screenshots**

--

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.2 (24C101)
 - PostgreSQL version 14.13
 - Version 3.6.2

**Additional context**

Originally introduced in this PR:

- https://github.com/ts-safeql/safeql/pull/359

**Comment by Newbie012** [comment]
fixed in 3.6.3

**Comment by karlhorky** [comment]
Hmm, still seeing this with `@ts-safeql/eslint-plugin@3.6.4` 🤔

Here's the minimal table definition, in case that works for reproducing for you:

```sql
CREATE TABLE event_rsvps (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY
);
```

**Comment by Newbie012** [comment]
does it still happening on 3.6.6? for some reason I was unable to reproduce it

**Comment by karlhorky** [comment]
I still see it on 3.6.6, yeah.

Is [`packages/generate/src/generate.test.ts`](https://github.com/ts-safeql/safeql/blob/main/packages/generate/src/generate.test.ts) the correct place for me to add a failing test? Eg:

1. Set up tables: https://github.com/ts-safeql/safeql/blob/39e978f4128ad0e76208e22b4cc509f17274b9fb/packages/generate/src/generate.test.ts#L14-L142
2. Test query against annotation: https://github.com/ts-safeql/safeql/blob/39e978f4128ad0e76208e22b4cc509f17274b9fb/packages/generate/src/generate.test.ts#L309-L319

**Comment by Newbie012** [comment]
Can you try [@ts-safeql/eslint-plugin@3.6.7](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%403.6.7)?

**Comment by karlhorky** [comment]
Still seeing [the failure with `boolean` vs `number`](https://github.com/ts-safeql/safeql/issues/362#issuecomment-2578777057) in [`@ts-safeql/eslint-plugin@3.6.7`](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%403.6.7):

![Image](https://github.com/user-attachments/assets/dd56d172-54dc-4bb5-8d0d-32dd1e349410)

Code for copy+paste:

```ts
  await sql`
    CREATE TABLE event_rsvps (
      id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      user_id integer NOT NULL REFERENCES users (id) ON DELETE cascade,
      event_id integer NOT NULL REFERENCES events (id) ON DELETE cascade,
      company_cohort_access_level_paid_id integer REFERENCES company_cohort_access_levels_paid (id),
      UNIQUE (user_id, event_id)
    )
  `;

  await sql<{ rsvped: boolean }[]>`
    SELECT
      x.*
    FROM
      (
        SELECT
          event_rsvps.id IS NOT NULL AS rsvped
        FROM
          event_rsvps
      ) x
  `;
```

**Comment by Newbie012** [comment]
Had some time this morning to tackle this issue again. Looking back, implementing [nested source resolution](https://github.com/ts-safeql/safeql/commit/42326c2ee1b0753a3dbd40c9942c8efa00f509a7) was a mistake—it only worked for actual columns, not expressions like `id is not null`. For now, I've reverted it to favor less strict inference over incorrect inference. A proper fix will require a more complex solution, which I'm planning on when I'll have time.

**Comment by Newbie012** [comment]
I believe this issue was resolved in recent releases. feel free to re-open the issue if it persists.

**Comment by karlhorky** [comment]
Thanks for the fix!

I can confirm that [`@ts-safeql/eslint-plugin@3.6.10`](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%403.6.10) now works with my reproduction above:

```ts
// ✅
await sql<{ rsvped: boolean }[]>`
  SELECT
    x.*
  FROM
    (
      SELECT
        event_rsvps.id IS NOT NULL AS rsvped
      FROM
        event_rsvps
    ) x
`
```
